# Generated by Django 6.0.7 on 2026-07-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notanizer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
