# Generated by Django 6.0.7 on 2026-07-26 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notanizer', '0003_alter_note_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notes/'),
        ),
        migrations.AddField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notes/image/'),
        ),
    ]
