# Generated by Django 6.0.7 on 2026-07-27 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notanizer', '0004_note_file_note_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='notes/files/'),
        ),
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='notes/images/'),
        ),
    ]
